import 'zone.js/dist/zone';
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { bootstrapApplication } from '@angular/platform-browser';

@Component({
  selector: 'my-app',
  standalone: true,
  imports: [CommonModule],
  template: `
  <div class="p-4 bg-gray-700 text-gray-400">Photo Gallery</div>

  <button class="px-4 py-2 mt-4 bg-green-300 hover:bg-green-600 text-gray-900 text-font-">Click Me</button>
  
  <p class="text-center text-xl font-bold text-gray-800">Hello, Tailwind CSS!</p>

  <div class=" codebox mt-4 -mx-4 sm:mx-0 lg:mt-0 lg:col-span-7 xl:col-span-6"><div class="relative overflow-hidden shadow-xl flex bg-slate-800 h-[31.625rem] max-h-[60vh] sm:max-h-[none] sm:rounded-xl lg:h-[34.6875rem] xl:h-[31.625rem] dark:bg-slate-900/70 dark:backdrop-blur dark:ring-1 dark:ring-inset dark:ring-white/10"><div class="relative w-full flex flex-col"><div class="flex-none border-b border-slate-500/30"><div class="flex items-center h-8 space-x-1.5 px-3"><div class="w-2.5 h-2.5 bg-slate-600 rounded-full"></div><div class="w-2.5 h-2.5 bg-slate-600 rounded-full"></div><div class="w-2.5 h-2.5 bg-slate-600 rounded-full"></div></div></div><div class="relative min-h-0 flex-auto flex flex-col"><div class="w-full flex-auto flex min-h-0 overflow-auto"><div class="w-full relative flex-auto"><pre class="flex min-h-full text-sm leading-6"><div aria-hidden="true" class="hidden md:block text-slate-600 flex-none py-4 pr-4 text-right select-none w-[3.125rem]">1<br>2<br>3<br>4<br>5<br>6<br>7<br>8<br>9<br>10<br>11<br>12<br>13<br>14<br>15<br>16<br>17<br>18<br>19<br>20<br>21<br>22<br>23<br>24<br>25<br>26<br>27<br>28<br>29<br>30<br>31<br>32<br>33<br>34<br>35<br>36<br>37<br>38<br>39<br>40<br>41<br>42<br>43<br>44<br>45<br>46<br>47<br>48<br>49<br>50<br>51<br>52<br>53<br>54<br>55<br>56<br>57<br>58<br>59<br>60<br>61<br>62<br>63<br>64<br>65<br>66<br>67<br>68<br>69<br>70<br>71</div><code class="flex-auto relative block text-slate-50 overflow-auto p-4"><span class="tag punctuation token">&lt;</span><span class="tag token">div</span><span class="tag token"> </span><span class="tag attr-name token">class</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">flex font-sans</span><span class="tag attr-value punctuation token">"</span><span class="tag punctuation token">&gt;</span><span></span>
<span>  </span><span class="tag punctuation token">&lt;</span><span class="tag token">div</span><span class="tag token"> </span><span class="tag attr-name token">class</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">flex-none w-48 relative</span><span class="tag attr-value punctuation token">"</span><span class="tag punctuation token">&gt;</span><span></span>
<span>    </span><span class="tag punctuation token">&lt;</span><span class="tag token">img</span><span class="tag token"> </span><span class="tag attr-name token">src</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">/classic-utility-jacket.jpg</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">alt</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">class</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">absolute inset-0 w-full h-full object-cover</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">loading</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">lazy</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag punctuation token">/&gt;</span><span></span>
<span>  </span><span class="tag punctuation token">&lt;/</span><span class="tag token">div</span><span class="tag punctuation token">&gt;</span><span></span>
<span>  </span><span class="tag punctuation token">&lt;</span><span class="tag token">form</span><span class="tag token"> </span><span class="tag attr-name token">class</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">flex-auto p-6</span><span class="tag attr-value punctuation token">"</span><span class="tag punctuation token">&gt;</span><span></span>
<span>    </span><span class="tag punctuation token">&lt;</span><span class="tag token">div</span><span class="tag token"> </span><span class="tag attr-name token">class</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">flex flex-wrap</span><span class="tag attr-value punctuation token">"</span><span class="tag punctuation token">&gt;</span><span></span>
<span>      </span><span class="tag punctuation token">&lt;</span><span class="tag token">h1</span><span class="tag token"> </span><span class="tag attr-name token">class</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">flex-auto text-lg font-semibold text-slate-900</span><span class="tag attr-value punctuation token">"</span><span class="tag punctuation token">&gt;</span><span></span>
        <span class="code-highlight animate-flash-code">Classic Utility Jacket</span>
<span>      </span><span class="tag punctuation token">&lt;/</span><span class="tag token">h1</span><span class="tag punctuation token">&gt;</span><span></span>
<span>      </span><span class="tag punctuation token">&lt;</span><span class="tag token">div</span><span class="tag token"> </span><span class="tag attr-name token">class</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">text-lg font-semibold text-slate-500</span><span class="tag attr-value punctuation token">"</span><span class="tag punctuation token">&gt;</span><span></span>
        <span class="code-highlight animate-flash-code">$110.00</span>
<span>      </span><span class="tag punctuation token">&lt;/</span><span class="tag token">div</span><span class="tag punctuation token">&gt;</span><span></span>
<span>      </span><span class="tag punctuation token">&lt;</span><span class="tag token">div</span><span class="tag token"> </span><span class="tag attr-name token">class</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">w-full flex-none text-sm font-medium text-slate-700 mt-2</span><span class="tag attr-value punctuation token">"</span><span class="tag punctuation token">&gt;</span><span></span>
<span>        In stock</span>
<span>      </span><span class="tag punctuation token">&lt;/</span><span class="tag token">div</span><span class="tag punctuation token">&gt;</span><span></span>
<span>    </span><span class="tag punctuation token">&lt;/</span><span class="tag token">div</span><span class="tag punctuation token">&gt;</span><span></span>
<span>    </span><span class="tag punctuation token">&lt;</span><span class="tag token">div</span><span class="tag token"> </span><span class="tag attr-name token">class</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">flex items-baseline mt-4 mb-6 pb-6 border-b border-slate-200</span><span class="tag attr-value punctuation token">"</span><span class="tag punctuation token">&gt;</span><span></span>
<span>      </span><span class="tag punctuation token">&lt;</span><span class="tag token">div</span><span class="tag token"> </span><span class="tag attr-name token">class</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">space-x-2 flex text-sm</span><span class="tag attr-value punctuation token">"</span><span class="tag punctuation token">&gt;</span><span></span>
<span>        </span><span class="tag punctuation token">&lt;</span><span class="tag token">label</span><span class="tag punctuation token">&gt;</span><span></span>
<span>          </span><span class="tag punctuation token">&lt;</span><span class="tag token">input</span><span class="tag token"> </span><span class="tag attr-name token">class</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">sr-only peer</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">name</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">size</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">type</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">radio</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">value</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">xs</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">checked</span><span class="tag token"> </span><span class="tag punctuation token">/&gt;</span><span></span>
<span>          </span><span class="tag punctuation token">&lt;</span><span class="tag token">div</span><span class="tag token"> </span><span class="tag attr-name token">class</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">w-9 h-9 rounded-lg flex items-center justify-center text-slate-700 peer-checked:font-semibold peer-checked:bg-slate-900 peer-checked:text-white</span><span class="tag attr-value punctuation token">"</span><span class="tag punctuation token">&gt;</span><span></span>
<span>            XS</span>
<span>          </span><span class="tag punctuation token">&lt;/</span><span class="tag token">div</span><span class="tag punctuation token">&gt;</span><span></span>
<span>        </span><span class="tag punctuation token">&lt;/</span><span class="tag token">label</span><span class="tag punctuation token">&gt;</span><span></span>
<span>        </span><span class="tag punctuation token">&lt;</span><span class="tag token">label</span><span class="tag punctuation token">&gt;</span><span></span>
<span>          </span><span class="tag punctuation token">&lt;</span><span class="tag token">input</span><span class="tag token"> </span><span class="tag attr-name token">class</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">sr-only peer</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">name</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">size</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">type</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">radio</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">value</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">s</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag punctuation token">/&gt;</span><span></span>
<span>          </span><span class="tag punctuation token">&lt;</span><span class="tag token">div</span><span class="tag token"> </span><span class="tag attr-name token">class</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">w-9 h-9 rounded-lg flex items-center justify-center text-slate-700 peer-checked:font-semibold peer-checked:bg-slate-900 peer-checked:text-white</span><span class="tag attr-value punctuation token">"</span><span class="tag punctuation token">&gt;</span><span></span>
<span>            S</span>
<span>          </span><span class="tag punctuation token">&lt;/</span><span class="tag token">div</span><span class="tag punctuation token">&gt;</span><span></span>
<span>        </span><span class="tag punctuation token">&lt;/</span><span class="tag token">label</span><span class="tag punctuation token">&gt;</span><span></span>
<span>        </span><span class="tag punctuation token">&lt;</span><span class="tag token">label</span><span class="tag punctuation token">&gt;</span><span></span>
<span>          </span><span class="tag punctuation token">&lt;</span><span class="tag token">input</span><span class="tag token"> </span><span class="tag attr-name token">class</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">sr-only peer</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">name</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">size</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">type</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">radio</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">value</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">m</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag punctuation token">/&gt;</span><span></span>
<span>          </span><span class="tag punctuation token">&lt;</span><span class="tag token">div</span><span class="tag token"> </span><span class="tag attr-name token">class</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">w-9 h-9 rounded-lg flex items-center justify-center text-slate-700 peer-checked:font-semibold peer-checked:bg-slate-900 peer-checked:text-white</span><span class="tag attr-value punctuation token">"</span><span class="tag punctuation token">&gt;</span><span></span>
<span>            M</span>
<span>          </span><span class="tag punctuation token">&lt;/</span><span class="tag token">div</span><span class="tag punctuation token">&gt;</span><span></span>
<span>        </span><span class="tag punctuation token">&lt;/</span><span class="tag token">label</span><span class="tag punctuation token">&gt;</span><span></span>
<span>        </span><span class="tag punctuation token">&lt;</span><span class="tag token">label</span><span class="tag punctuation token">&gt;</span><span></span>
<span>          </span><span class="tag punctuation token">&lt;</span><span class="tag token">input</span><span class="tag token"> </span><span class="tag attr-name token">class</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">sr-only peer</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">name</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">size</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">type</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">radio</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">value</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">l</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag punctuation token">/&gt;</span><span></span>
<span>          </span><span class="tag punctuation token">&lt;</span><span class="tag token">div</span><span class="tag token"> </span><span class="tag attr-name token">class</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">w-9 h-9 rounded-lg flex items-center justify-center text-slate-700 peer-checked:font-semibold peer-checked:bg-slate-900 peer-checked:text-white</span><span class="tag attr-value punctuation token">"</span><span class="tag punctuation token">&gt;</span><span></span>
<span>            L</span>
<span>          </span><span class="tag punctuation token">&lt;/</span><span class="tag token">div</span><span class="tag punctuation token">&gt;</span><span></span>
<span>        </span><span class="tag punctuation token">&lt;/</span><span class="tag token">label</span><span class="tag punctuation token">&gt;</span><span></span>
<span>        </span><span class="tag punctuation token">&lt;</span><span class="tag token">label</span><span class="tag punctuation token">&gt;</span><span></span>
<span>          </span><span class="tag punctuation token">&lt;</span><span class="tag token">input</span><span class="tag token"> </span><span class="tag attr-name token">class</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">sr-only peer</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">name</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">size</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">type</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">radio</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">value</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">xl</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag punctuation token">/&gt;</span><span></span>
<span>          </span><span class="tag punctuation token">&lt;</span><span class="tag token">div</span><span class="tag token"> </span><span class="tag attr-name token">class</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">w-9 h-9 rounded-lg flex items-center justify-center text-slate-700 peer-checked:font-semibold peer-checked:bg-slate-900 peer-checked:text-white</span><span class="tag attr-value punctuation token">"</span><span class="tag punctuation token">&gt;</span><span></span>
<span>            XL</span>
<span>          </span><span class="tag punctuation token">&lt;/</span><span class="tag token">div</span><span class="tag punctuation token">&gt;</span><span></span>
<span>        </span><span class="tag punctuation token">&lt;/</span><span class="tag token">label</span><span class="tag punctuation token">&gt;</span><span></span>
<span>      </span><span class="tag punctuation token">&lt;/</span><span class="tag token">div</span><span class="tag punctuation token">&gt;</span><span></span>
<span>    </span><span class="tag punctuation token">&lt;/</span><span class="tag token">div</span><span class="tag punctuation token">&gt;</span><span></span>
<span>    </span><span class="tag punctuation token">&lt;</span><span class="tag token">div</span><span class="tag token"> </span><span class="tag attr-name token">class</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">flex space-x-4 mb-6 text-sm font-medium</span><span class="tag attr-value punctuation token">"</span><span class="tag punctuation token">&gt;</span><span></span>
<span>      </span><span class="tag punctuation token">&lt;</span><span class="tag token">div</span><span class="tag token"> </span><span class="tag attr-name token">class</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">flex-auto flex space-x-4</span><span class="tag attr-value punctuation token">"</span><span class="tag punctuation token">&gt;</span><span></span>
<span>        </span><span class="tag punctuation token">&lt;</span><span class="tag token">button</span><span class="tag token"> </span><span class="tag attr-name token">class</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">h-10 px-6 font-semibold rounded-md bg-black text-white</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">type</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">submit</span><span class="tag attr-value punctuation token">"</span><span class="tag punctuation token">&gt;</span><span></span>
<span>          Buy now</span>
<span>        </span><span class="tag punctuation token">&lt;/</span><span class="tag token">button</span><span class="tag punctuation token">&gt;</span><span></span>
<span>        </span><span class="tag punctuation token">&lt;</span><span class="tag token">button</span><span class="tag token"> </span><span class="tag attr-name token">class</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">h-10 px-6 font-semibold rounded-md border border-slate-200 text-slate-900</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">type</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">button</span><span class="tag attr-value punctuation token">"</span><span class="tag punctuation token">&gt;</span><span></span>
<span>          Add to bag</span>
<span>        </span><span class="tag punctuation token">&lt;/</span><span class="tag token">button</span><span class="tag punctuation token">&gt;</span><span></span>
<span>      </span><span class="tag punctuation token">&lt;/</span><span class="tag token">div</span><span class="tag punctuation token">&gt;</span><span></span>
<span>      </span><span class="tag punctuation token">&lt;</span><span class="tag token">button</span><span class="tag token"> </span><span class="tag attr-name token">class</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">flex-none flex items-center justify-center w-9 h-9 rounded-md text-slate-300 border border-slate-200</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">type</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">button</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">aria-label</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">Like</span><span class="tag attr-value punctuation token">"</span><span class="tag punctuation token">&gt;</span><span></span>
<span>        </span><span class="tag punctuation token">&lt;</span><span class="tag token">svg</span><span class="tag token"> </span><span class="tag attr-name token">width</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">20</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">height</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">20</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">fill</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">currentColor</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">aria-hidden</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">true</span><span class="tag attr-value punctuation token">"</span><span class="tag punctuation token">&gt;</span><span></span>
<span>          </span><span class="tag punctuation token">&lt;</span><span class="tag token">path</span><span class="tag token"> </span><span class="tag attr-name token">fill-rule</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">evenodd</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">clip-rule</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">evenodd</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag attr-name token">d</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="tag attr-value token">M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z</span><span class="tag attr-value punctuation token">"</span><span class="tag token"> </span><span class="tag punctuation token">/&gt;</span><span></span>
<span>        </span><span class="tag punctuation token">&lt;/</span><span class="tag token">svg</span><span class="tag punctuation token">&gt;</span><span></span>
<span>      </span><span class="tag punctuation token">&lt;/</span><span class="tag token">button</span><span class="tag punctuation token">&gt;</span><span></span>
<span>    </span><span class="tag punctuation token">&lt;/</span><span class="tag token">div</span><span class="tag punctuation token">&gt;</span><span></span>
<span>    </span><span class="tag punctuation token">&lt;</span><span class="tag token">p</span><span class="tag token"> </span><span class="tag attr-name token">class</span><span class="tag attr-value punctuation attr-equals token">=</span><span class="tag attr-value punctuation token">"</span><span class="code-highlight tag attr-value token animate-flash-code">text-sm text-slate-700</span><span class="tag attr-value punctuation token">"</span><span class="tag punctuation token">&gt;</span><span></span>
<span>      Free shipping on all continental US orders.</span>
<span>    </span><span class="tag punctuation token">&lt;/</span><span class="tag token">p</span><span class="tag punctuation token">&gt;</span><span></span>
<span>  </span><span class="tag punctuation token">&lt;/</span><span class="tag token">form</span><span class="tag punctuation token">&gt;</span><span></span>
<span></span><span class="tag punctuation token">&lt;/</span><span class="tag token">div</span><span class="tag punctuation token">&gt;</span><span></span>
<span class="inline-block"></span>
</code></pre></div></div></div></div></div></div>
  `,
})
export class App {
  name = 'Angular';
}

bootstrapApplication(App);
